#cloud-config
package_update: true
packages:
  - squid

write_files:
  - path: /etc/squid/squid.conf
    permissions: '0644'
    owner: root:root
    content: |
      http_port 3128

      acl jissou_network src 10.0.1.0/24
      acl jissou_denylist dstdomain identity.7.azurestaticapps.net
      acl jissou_allowlist dstdomain github.com
      acl jissou_allowlist dstdomain graph.microsoft.com
      acl jissou_allowlist dstdomain login.microsoftonline.com
      acl jissou_allowlist dstdomain management.azure.com
      acl jissou_allowlist dstdomain management.core.windows.net
      acl jissou_allowlist dstdomain registry.npmjs.org
      acl jissou_allowlist dstdomain .azurewebsites.net
      acl jissou_allowlist dstdomain aka.ms
      acl jissou_allowlist dstdomain .azurefd.net
      acl jissou_allowlist dstdomain json.schemastore.org
      acl jissou_allowlist dstdomain .azureedge.net
      acl jissou_allowlist dstdomain .azurestaticapps.net
      acl jissou_allowlist dstdomain .blob.core.windows.net
      acl jissou_allowlist dstdomain nodejs.org
      acl jissou_allowlist dstdomain release-assets.githubusercontent.com
      acl allowed_http_ports port 80
      acl allowed_https_ports port 443
      acl CONNECT method CONNECT

      http_access deny jissou_network jissou_denylist
      http_access allow jissou_network jissou_allowlist allowed_http_ports
      http_access allow jissou_network jissou_allowlist allowed_https_ports CONNECT
      http_access deny all

      access_log /var/log/squid/access.log

runcmd:
  - squid -k parse
  - systemctl enable squid
  - systemctl restart squid
